Multi template
Public-Health-Bioinformatics/DataHarmonizer pull request #104
Opened 2020-09-27 19:25 UTC by ddooley

Just for preliminary comments.  May hide Template menu until other templates are ready.

2020-10-05 16:20 UTC, ivansg44 requested changes
I appreciate the effort that went into this PR, and the template switching functionality seems to be working well (although there are a couple things I think you could do to improve it, mentioned at the end of this review). However, I believe more existing code is being modified in this PR than necessary. The codebase is relatively mature, so we should focus on a couple things:

1) One PR for one thing (i.e., avoid introducing sweeping changes in a single PR)
2) Extending--not modifying--the existing code

With regards to point #1, I believe we should discuss this URL parameter business, and implement it if necessary in another PR. We should just focus on UI-driven template switching in this one. I'm not convinced we need to worry about URL parameters for an application that is meant to be run locally.

With regards to point #2, I believe the point of entry in this function (you refer to it in the code as "application launch") has been modified more than necessary. Modifying existing code in a relatively mature codebase is always risky, because you can accidentally introduce bugs and break previously stable functionality. It also makes it quite difficult to review the changes, when you're also introducing a new functionality on top of this re-structuring. If there is a need to further modularize the point-of-entry, I think it should be strongly justified and in a separate PR, where we can test it thoroughly.

Here's how I would have done things:

- New JSON file
	- Keys = template names
	- Values = path to data and export
- windows.TEMPLATES = reference to data in json file, called in document.ready()
- window.TEMPLATE = (some function), called in document.ready()
	- This function takes two parameters (template name, and TEMPLATES)
	- This function returns the necessary DATA and EXPORT variables
- (some function) is also called later in document.ready(), in a codeblock similar to the ones that are already there for existing parts of the upper toolbar
	- followed by HOT.render()

Essentially, the existing code remains largely the same, with a few additions to document.ready(), and the function(s) related to switching templates kept separate from the existing code. I understand that Settings->Jump to... needs to change with the template, but I think that can be done simply by adding some sort of hook.

Couple of things I would to do to improve template switching:

1) Some sort of warning when users switch templates, if there is data in the grid
2) Move the option to switch templates under settings in the toolbar, rather than add it on the top-left

With regards to #1, see #clear-data-warning-modal and #save-as-invalid-warning-modal for precedent.

With regards to #2, my justification is based on two points. First, it keeps all the screenshots/gifs in existing documentation similar to the current UI. We can add new screenshots/gifs for this new functionality easily, but it would be a bigger pain to go change everything from previous versions. Second, it keeps the UI consistent with other spreadsheet editors, which was what I envisioned when designing this application. They usually have a tool bar on the top, with File on the left, then settings, and then help.

I do think it is important to keep the name of the current template visible to the user at all times though. Maybe the name of the current template could be on the bottom right, below the grid. That's not a big change from interfaces in our previous releases.

One last thing: I have been using the Google Style guide for HTML, CSS and JS to keep the codebase relatively uniform and consistent. I think you should follow this guide and any precedents set by the existing code, to keep the code easy-to-navigate for us and future collaboraters. Some issues I noticed were:

- Not using arrow functions, or declaring functions as constants
- Using var, instead of let and const
- Lines past the length limit
- If-statements across 2 lines without curly braces
- Uneven white-space between functions

2020-10-06 15:10 UTC, ddooley commented on main.css
> +#add-rows-input {max-width:5rem}
The adjustment was not to the grid but to the element inside the grid.

2020-10-06 15:12 UTC, ddooley commented on main.html
> +              <span class="input-group-text"> rows at the bottom.</span>
Ok

2020-10-06 15:18 UTC, ddooley commented on script/main.js
> +  $('#file-dropdown-btn-group').off()
Yes.  Any function call which adds event handlers to HTML elements, if the elements aren't themselves destroyed, and the function call is repeated, causes duplicate handlers, which may be bad for performance, and can lead to other bad stuff.

2020-10-06 15:19 UTC, ddooley commented on script/main.js
> +
Ok

2020-10-06 15:23 UTC, ddooley commented on script/main.js
> +dataOnload = function () {
good catch; I've done it on my side.

2020-10-06 15:30 UTC, ddooley commented on script/main.js
> +
Originally it was a larger function but now that it is winnowed down, sure.

2020-10-06 15:32 UTC, ddooley commented on script/main.js
> +exportOnload = function () {
done on my side.

2020-10-06 15:33 UTC, ddooley commented on script/main.js
> +  }
getting rid of old selection options in html element before adding new ones.

2020-10-06 15:34 UTC, ddooley commented on script/main.js
> +    select.append(new Option(option,option))
There will never be long lists of export formats beyond 5 or 10 elements say, so performance won't be a factor.

2020-10-06 15:35 UTC, ddooley commented on script/main.js
> +/************************** APPLICATION LAUNCH ********************/
I was finding it difficult to scroll down and see where exactly the application launch section started so I emphasized it more.

2020-10-06 15:40 UTC, ddooley commented on script/main.js
> +    alert (`Template "${template}" is not listed in DataHarmonizer so might not load! `);
It was a quick message that would almost never appear for users unless we hardcoded a menu item that didn't have a template for it.  So I wasn't factoring user-facing appearance.  But I'll change it to a modal if you want.

2020-10-06 15:43 UTC, ddooley commented on script/main.js
> +      EXPORT_FORMATS[exportFormat](baseName, HOT, DATA, XLSX);
done

2020-10-06 15:44 UTC, ddooley commented on script/main.js
> + * @param {String} template: path of template starting from app's template folder.
done

2020-10-06 16:13 UTC, ddooley commented
This pr I should have marked WIP. Its meant to be a design iteration to be discussed. I wrote it in a day.
- I tried to follow your / Google code pattern but neglected a few things here and there, so thanks for noting those spots.
- Re. modal - the alert isn't something a user would see normally; it was more a programmer level message. but I've done the change.
- Re. template via URI. Its a feature I popped in there to show how we can handle templates that don't necessarily appear in menu system.
- Re. display/selection of templates in menu vs in setup vs. title somewhere on screen.  Totally a point of discussion as I mentioned in the pr. A decision we can all dwell over.
- Re. mature code base. The main problem with the current code base was that the startup part had a variety of jquery html handler connections that are only run once, mixed in with html setup stuff that needed to be rerun on each template load. So I separated those out.  Secondly I had to split into a few stages the code that loads the template json/js and then do stuff after the load.  I think you would discover that you would have to do the very same things, so it wasn't a capricious reorganization.
- As to the suggestion of a TEMPLATE data structure, with functions inside it and data.js too, I agree, we can head in that kind of direction.  That exposes that the code could be refactored in a more modular way as a class with data components, initializers etc. I didn't have time to go that far.

2020-10-21 18:00 UTC, ddooley commented
Note that some data structures and functions require "var" definitions in certain cases for objects and functions where js scripts are reloaded, otherwise javascript throws an error

2020-11-04 00:25 UTC, ddooley commented
I've changed the template selection menu to be in a modal, which also enables another checkbox option to view under-development templates as well.

2020-11-04 02:04 UTC, merged